# Generated by Django 6.0.7 on 2026-07-20 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='focus_areas',
            field=models.ManyToManyField(blank=True, help_text='Focus areas that this course directly supports.', related_name='courses', to='program.focusarea'),
        ),
        migrations.AddField(
            model_name='facility',
            name='focus_areas',
            field=models.ManyToManyField(blank=True, help_text='Focus areas that use this equipment or facility.', related_name='facilities', to='program.focusarea'),
        ),
        migrations.AddField(
            model_name='facility',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this equipment item in the homepage learning environment section.'),
        ),
        migrations.CreateModel(
            name='FocusAreaDetailItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('item_type', models.CharField(choices=[('outcome', 'Learning outcome'), ('activity', 'Learning activity'), ('career', 'Career pathway')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('focus_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_items', to='program.focusarea')),
            ],
            options={
                'verbose_name': 'Focus area detail',
                'ordering': ('sort_order', 'pk'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('focus_area', 'item_type', 'title'), name='unique_focus_detail_item')],
            },
        ),
    ]
