# Generated by Django 6.0.7 on 2026-08-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_research_editorial_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='courses_taught',
            field=models.TextField(blank=True, help_text='One entry per line.'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='credentials',
            field=models.CharField(blank=True, help_text='Post-nominal qualification, for example Ph.D. or M.Eng.', max_length=80),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='education',
            field=models.TextField(blank=True, help_text='One qualification per line, for example: Ph.D. Mechanical Engineering, University, 2018'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='office',
            field=models.CharField(blank=True, help_text='Room or building, for example Engineering Building, Room 204.', max_length=120),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='profile_url',
            field=models.URLField(blank=True, help_text='Optional external profile, for example Google Scholar or ORCID.'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='publications',
            field=models.TextField(blank=True, help_text='One entry per line.'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='research_interests',
            field=models.TextField(blank=True, help_text='One entry per line.'),
        ),
        migrations.AddField(
            model_name='facultymember',
            name='slug',
            field=models.SlugField(blank=True, max_length=180),
        ),
    ]
