# Generated by Django 6.0.7 on 2026-08-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_faculty_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='statement',
            field=models.TextField(blank=True, help_text='One sentence shown as the large heading on the profile page, for example: Sophy Soun connects engineering theory with experimentation and practical laboratory learning. Left blank, the first sentence of the biography is used.'),
        ),
    ]
