# Generated by Django 6.0.7 on 2026-08-04 11:04

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_facultymember_statement'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('badge', models.CharField(default='Research project', help_text='Label on the gold tab, for example Teaching & research.', max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('meta', models.CharField(blank=True, help_text='Small underlined line above the title, for example Automation · Environmental control.', max_length=120)),
                ('link_url', models.CharField(blank=True, help_text='Where the card goes. A path on this site such as /research/projects/metal-recycling, or a full external address.', max_length=300)),
                ('link_label', models.CharField(blank=True, default='Explore the work', help_text='Text of the link at the foot of the card.', max_length=60)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('member', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='program.facultymember')),
            ],
            options={
                'verbose_name': 'Faculty work card',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
