# Generated by Django 6.0.7 on 2026-08-04 13:26

import json
import uuid

import wagtail.fields
from django.db import migrations, models


def richtext_to_stream(apps, schema_editor):
    """Keep any body written before the switch to blocks.

    The column stores rich-text HTML today and StreamField JSON afterwards, so
    existing copy is wrapped in a single paragraph block rather than left as
    text a StreamField cannot parse. Runs before the field is altered, while
    the historical model still treats the column as plain text.
    """
    NewsEvent = apps.get_model("program", "NewsEvent")
    for entry in NewsEvent.objects.exclude(body=""):
        body = (entry.body or "").strip()
        if not body or body.startswith("["):
            continue
        entry.body = json.dumps(
            [{"type": "paragraph", "value": body, "id": str(uuid.uuid4())}]
        )
        entry.save(update_fields=["body"])


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_facultyworkitem'),
    ]

    operations = [
        migrations.RunPython(
            richtext_to_stream,
            migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.AddField(
            model_name='newsevent',
            name='category',
            field=models.CharField(blank=True, help_text='Small gold label above the title, for example Projects & Community or International Engagement. Free text, so the section can carry more than news.', max_length=80),
        ),
        migrations.AddField(
            model_name='programsettings',
            name='news_section_cta_label',
            field=models.CharField(default='View all stories', max_length=60),
        ),
        migrations.AddField(
            model_name='programsettings',
            name='news_section_eyebrow',
            field=models.CharField(default='Latest news & activities', max_length=120),
        ),
        migrations.AddField(
            model_name='programsettings',
            name='news_section_heading',
            field=models.CharField(default='Mechanical Engineering in action', max_length=220),
        ),
        migrations.AddField(
            model_name='programsettings',
            name='news_section_intro',
            field=models.TextField(default='Explore our latest projects, learning experiences, partnerships, and contributions to industry and the community.'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('quote', 8), ('video', 11), ('document', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Section heading', 'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Text'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown under the image.', 'max_length': 250, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describes the image for screen readers. Leave empty if the image is decorative and the caption already says what it shows.', 'max_length': 250, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('alt_text', 4)]], {}), 6: ('wagtail.blocks.TextBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('text', 6), ('attribution', 7)]], {}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'A YouTube, Vimeo, or Facebook video link.'}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('url', 9), ('caption', 10)]], {}), 12: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text on the download link. Defaults to the document title.', 'max_length': 120, 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('document', 12), ('label', 13)]], {})}, help_text='The story itself. Add blocks, and drag them by the handle at the top right of each block to rearrange.'),
        ),
    ]
