# Generated by Django 6.0.7 on 2026-08-04 16:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_newsevent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='author',
            field=models.CharField(blank=True, help_text='Byline shown under the headline, for example Sok Dara, Communications Officer.', max_length=160),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('gallery', 10), ('quote', 13), ('video', 15), ('document', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Section heading', 'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Text'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown under the image.', 'max_length': 250, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describes the image for screen readers. Leave empty if the image is decorative and the caption already says what it shows.', 'max_length': 250, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('alt_text', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 2), ('alt_text', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'max_num': 3, 'min_num': 2}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown under the row.', 'max_length': 250, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('images', 8), ('caption', 9)]], {}), 11: ('wagtail.blocks.TextBlock', (), {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('text', 11), ('attribution', 12)]], {}), 14: ('wagtail.blocks.URLBlock', (), {'help_text': 'A YouTube, Vimeo, or Facebook video link.'}), 15: ('wagtail.blocks.StructBlock', [[('url', 14), ('caption', 6)]], {}), 16: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text on the download link. Defaults to the document title.', 'max_length': 120, 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('document', 16), ('label', 17)]], {})}, help_text='The story itself. Add blocks, and drag them by the handle at the top right of each block to rearrange.'),
        ),
    ]
