# Generated by Django 6.0.7 on 2026-08-06 09:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_newsevent_author_alter_newsevent_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('gallery', 10), ('media_gallery', 16), ('quote', 19), ('video', 14), ('document', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Section heading', 'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Text'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown under the image.', 'max_length': 250, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describes the image for screen readers. Leave empty if the image is decorative and the caption already says what it shows.', 'max_length': 250, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('alt_text', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 2), ('alt_text', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'max_num': 3, 'min_num': 2}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown under the row.', 'max_length': 250, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('images', 8), ('caption', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 12: ('wagtail.blocks.URLBlock', (), {'help_text': 'A YouTube, Vimeo, or Facebook video link.'}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Still shown before the video is played. YouTube links use their own thumbnail when this is empty.', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('url', 12), ('caption', 6), ('poster', 13)]], {}), 15: ('wagtail.blocks.StreamBlock', [[('image', 5), ('video', 14)]], {'min_num': 1}), 16: ('wagtail.blocks.StructBlock', [[('heading', 11), ('items', 15), ('caption', 6)]], {}), 17: ('wagtail.blocks.TextBlock', (), {}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('text', 17), ('attribution', 18)]], {}), 20: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text on the download link. Defaults to the document title.', 'max_length': 120, 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('document', 20), ('label', 21)]], {})}, help_text='The story itself. Add blocks, and drag them by the handle at the top right of each block to rearrange.'),
        ),
    ]
