# Generated by Django 6.0.7 on 2026-08-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_alter_newsevent_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='announce',
            field=models.BooleanField(default=False, help_text='Surfaces this entry in the small card at the corner of the homepage, for something a visitor should not have to scroll to find. An event stops showing once its date has passed.', verbose_name='Show in the announcement card'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='announcement_cta',
            field=models.CharField(blank=True, help_text='Button on the announcement card. Defaults to Event details.', max_length=40),
        ),
    ]
