# Generated by Django 6.0.7 on 2026-08-07 10:14

import json
import uuid

import wagtail.fields
from django.db import migrations


def richtext_to_stream(apps, schema_editor):
    """Rewrite every body as valid JSON before the column becomes a StreamField.

    A StreamField is JSON-backed and SQLite enforces that with a
    CHECK (JSON_VALID(...)) constraint, so *every* row has to be converted --
    including the empty ones, since "" is not valid JSON and the table rebuild
    fails on it. Existing copy is wrapped in a single text block so nothing an
    author wrote is lost.

    Runs before the field is altered, while the historical model still treats
    the column as plain text.
    """
    ResearchProject = apps.get_model("program", "ResearchProject")
    for entry in ResearchProject.objects.all():
        body = (entry.body or "").strip()
        if body.startswith("[") or body.startswith("{"):
            continue
        entry.body = (
            json.dumps([{"type": "paragraph", "value": body, "id": str(uuid.uuid4())}])
            if body
            else "[]"
        )
        entry.save(update_fields=["body"])


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_newsevent_announce_newsevent_announcement_cta'),
    ]

    operations = [
        migrations.RunPython(
            richtext_to_stream,
            migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('gallery', 10), ('media_gallery', 16), ('quote', 19), ('video', 14), ('document', 22), ('key_facts', 28), ('stats', 33), ('steps', 39), ('table', 41), ('callout', 43), ('references', 48)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Section heading', 'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Text'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown under the image.', 'max_length': 250, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describes the image for screen readers. Leave empty if the image is decorative and the caption already says what it shows.', 'max_length': 250, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('alt_text', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 2), ('alt_text', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'max_num': 3, 'min_num': 2}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown under the row.', 'max_length': 250, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('images', 8), ('caption', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 12: ('wagtail.blocks.URLBlock', (), {'help_text': 'A YouTube, Vimeo, or Facebook video link.'}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Still shown before the video is played. YouTube links use their own thumbnail when this is empty.', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('url', 12), ('caption', 6), ('poster', 13)]], {}), 15: ('wagtail.blocks.StreamBlock', [[('image', 5), ('video', 14)]], {'min_num': 1}), 16: ('wagtail.blocks.StructBlock', [[('heading', 11), ('items', 15), ('caption', 6)]], {}), 17: ('wagtail.blocks.TextBlock', (), {}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('text', 17), ('attribution', 18)]], {}), 20: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text on the download link. Defaults to the document title.', 'max_length': 120, 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('document', 20), ('label', 21)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'Project facts', 'max_length': 200, 'required': False}), 24: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 25: ('wagtail.blocks.CharBlock', (), {'max_length': 300}), 26: ('wagtail.blocks.StructBlock', [[('label', 24), ('value', 25)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {'min_num': 1}), 28: ('wagtail.blocks.StructBlock', [[('heading', 23), ('facts', 27)]], {}), 29: ('wagtail.blocks.CharBlock', (), {'help_text': 'For example 42% or 1.8 kW.', 'max_length': 40}), 30: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 31: ('wagtail.blocks.StructBlock', [[('value', 29), ('label', 30)]], {}), 32: ('wagtail.blocks.ListBlock', (31,), {'max_num': 4, 'min_num': 2}), 33: ('wagtail.blocks.StructBlock', [[('heading', 11), ('stats', 32)]], {}), 34: ('wagtail.blocks.CharBlock', (), {'default': 'Method', 'max_length': 200, 'required': False}), 35: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 36: ('wagtail.blocks.TextBlock', (), {'required': False}), 37: ('wagtail.blocks.StructBlock', [[('title', 35), ('description', 36)]], {}), 38: ('wagtail.blocks.ListBlock', (37,), {'min_num': 1}), 39: ('wagtail.blocks.StructBlock', [[('heading', 34), ('steps', 38)]], {}), 40: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 41: ('wagtail.blocks.StructBlock', [[('heading', 11), ('table', 40), ('caption', 6)]], {}), 42: ('wagtail.blocks.CharBlock', (), {'default': 'Note', 'max_length': 60, 'required': False}), 43: ('wagtail.blocks.StructBlock', [[('label', 42), ('text', 17)]], {}), 44: ('wagtail.blocks.CharBlock', (), {'default': 'Publications and references', 'max_length': 200, 'required': False}), 45: ('wagtail.blocks.URLBlock', (), {'required': False}), 46: ('wagtail.blocks.StructBlock', [[('citation', 17), ('url', 45)]], {}), 47: ('wagtail.blocks.ListBlock', (46,), {'min_num': 1}), 48: ('wagtail.blocks.StructBlock', [[('heading', 44), ('entries', 47)]], {})}, help_text='The project write-up. Add blocks, and drag them by the handle at the top right of each block to rearrange.'),
        ),
    ]
