# Generated by Django 6.0.7 on 2026-08-09 03:00

import program.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0018_newseventgalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsevent',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('gallery', 10), ('media_gallery', 17), ('collection_gallery', 19), ('quote', 22), ('video', 15), ('document', 25), ('story_gallery', 27)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Section heading', 'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Text'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown under the image.', 'max_length': 250, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describes the image for screen readers. Leave empty if the image is decorative and the caption already says what it shows.', 'max_length': 250, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('alt_text', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 2), ('alt_text', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'max_num': 3, 'min_num': 2}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown under the row.', 'max_length': 250, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('images', 8), ('caption', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 12: ('wagtail.blocks.URLBlock', (), {'help_text': 'A YouTube, Vimeo, or Facebook link. Leave empty if uploading a file.', 'required': False}), 13: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'An uploaded .mp4 or .webm, up to 100MB. Used when there is no link.', 'required': False}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Still shown before the video is played. YouTube links use their own thumbnail when this is empty.', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('url', 12), ('video_file', 13), ('caption', 6), ('poster', 14)]], {}), 16: ('wagtail.blocks.StreamBlock', [[('image', 5), ('video', 15)]], {'min_num': 1}), 17: ('wagtail.blocks.StructBlock', [[('heading', 11), ('items', 16), ('caption', 6)]], {}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': program.blocks.collection_choices, 'help_text': 'Images uploaded into this collection are shown, newest last.'}), 19: ('wagtail.blocks.StructBlock', [[('heading', 11), ('collection', 18), ('caption', 6)]], {}), 20: ('wagtail.blocks.TextBlock', (), {}), 21: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('text', 20), ('attribution', 21)]], {}), 23: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text on the download link. Defaults to the document title.', 'max_length': 120, 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('document', 23), ('label', 24)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'Gallery', 'max_length': 200, 'required': False}), 27: ('wagtail.blocks.StructBlock', [[('heading', 26), ('caption', 6)]], {})}, help_text='The story itself. Add blocks, and drag them by the handle at the top right of each block to rearrange.'),
        ),
    ]
