# Generated by Django 6.0.7 on 2026-08-16 15:58

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0019_alter_newsevent_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='employment_type',
            field=models.CharField(blank=True, help_text='For example Full-time, Part-time, or 6-month internship. Shown on the card beside the location.', max_length=80),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='how_to_apply',
            field=wagtail.fields.RichTextField(blank=True, help_text='What an applicant should send and where. Used when there is no application link to send them to.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='positions',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of openings, if the partner has stated one.', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='requirements',
            field=wagtail.fields.RichTextField(blank=True, help_text='Qualifications, skills and experience expected.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='responsibilities',
            field=wagtail.fields.RichTextField(blank=True, help_text='What the person will do. A bulleted list reads best.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source_name',
            field=models.CharField(blank=True, help_text="Where this announcement was published, for example the partner's careers page or a Telegram post.", max_length=120),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='source_url',
            field=models.URLField(blank=True, help_text='Link to the original announcement.'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='Set automatically when an announcement is imported from a partner source. Empty means it was entered by hand.', null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Full description of the role, shown on the detail page.'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Nothing appears on the site until this is ticked, including imported announcements: a partner posting on a university site is reviewed first.'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='summary',
            field=models.TextField(help_text='One or two sentences describing the role. Shown on the card, so keep it short: the full description belongs below.'),
        ),
    ]
