# Generated by Django 6.0.7 on 2026-08-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0021_researchproject_keywords_researchproject_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='period',
            field=models.CharField(blank=True, help_text='For work that ran over months rather than on a day, for example May 2025 - June 2026. Shown instead of the date. Leave empty for anything that happened on one day.', max_length=80, verbose_name='Activity period'),
        ),
    ]
