# Generated by Django 6.0.7 on 2026-08-20 04:16

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0022_newsevent_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('category', models.CharField(choices=[('admissions', 'Admissions'), ('program', 'The program'), ('learning', 'Teaching and learning'), ('facilities', 'Facilities and equipment'), ('careers', 'Careers'), ('support', 'Fees and support')], default='admissions', help_text='Groups the question on the FAQ page.', max_length=20)),
                ('question', models.CharField(max_length=300)),
                ('answer', wagtail.fields.RichTextField(blank=True, help_text='Left empty, the question stays off the site however this is ticked. Answer it, then publish.')),
                ('is_published', models.BooleanField(default=False, help_text='Published questions appear on the FAQ page once answered.')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ('sort_order', 'pk'),
                'abstract': False,
            },
        ),
    ]
