# Generated by Django 6.0.7 on 2026-08-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0023_faqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymember',
            name='research_projects',
            field=models.ManyToManyField(blank=True, help_text="Tick the projects this person actually works on. These appear in the Selected work row. Leave empty and the row is left out entirely, rather than filled with the focus area's own copy.", related_name='faculty', to='program.researchproject', verbose_name='Research projects'),
        ),
    ]
