# Generated by Django 6.0.7 on 2026-08-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0024_facultymember_research_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='announcement_url',
            field=models.URLField(blank=True, help_text="Where the announcement card's Register button goes. Leave empty and the card offers only the event page.", verbose_name='Registration link'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='venue',
            field=models.CharField(blank=True, help_text='Where it happens, for example ME CDIO Learning Workspace. Shown on the announcement card beside the time.', max_length=180),
        ),
    ]
