# Generated by Django 6.0.7 on 2026-08-23 16:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0025_newsevent_announcement_url_newsevent_venue'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Leads the landing page's research band. One project at a time -- the first ticked wins, so a story is told properly rather than four told thinly.", verbose_name='Show on the landing page'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='landing_story',
            field=wagtail.fields.StreamField([('steps', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Method', 'max_length': 200, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'min_num': 1}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('steps', 4)]], {})}, help_text='The few steps that carry this project on the landing page: the problem, what was built, and where it ended up. Written for somebody deciding whether to apply, not for a reviewer.', verbose_name='Landing page story'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='platform_label',
            field=models.CharField(blank=True, help_text='What that link is called, for example FarmOS. Say plainly if it needs an account.', max_length=80),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='platform_url',
            field=models.URLField(blank=True, help_text='A system built for this project that a reader can go and look at.'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='showcase_image',
            field=models.ForeignKey(blank=True, help_text='The picture the landing page leads with -- a dashboard, a rig, the thing itself. Falls back to the project image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
