# Generated by Django 6.0.7 on 2026-09-09 16:24

import program.blocks
import wagtail.fields
from django.db import migrations, models
from django.utils.text import slugify


def fill_slugs(apps, schema_editor):
    """Give the machines already in the catalogue an address.

    The column arrives blank on every existing row, so it cannot be made unique
    until each one has been filled. Names collide rarely but they do collide --
    two "Hydraulic System" entries would produce the same slug -- so a numeric
    suffix settles ties in catalogue order.
    """
    Facility = apps.get_model("program", "Facility")
    taken = set()
    for facility in Facility.objects.order_by("sort_order", "pk"):
        base = slugify(facility.name)[:190] or "machine"
        candidate = base
        suffix = 2
        while candidate in taken:
            candidate = f"{base}-{suffix}"
            suffix += 1
        taken.add(candidate)
        facility.slug = candidate
        facility.save(update_fields=["slug"])


def clear_slugs(apps, schema_editor):
    apps.get_model("program", "Facility").objects.update(slug="")


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0026_researchproject_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='detail',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('gallery', 10), ('media_gallery', 17), ('collection_gallery', 19), ('quote', 22), ('video', 15), ('document', 25), ('key_facts', 31), ('stats', 36), ('steps', 42), ('team', 49), ('timeline', 55), ('table', 57), ('callout', 59), ('references', 64)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Section heading', 'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Text'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown under the image.', 'max_length': 250, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Describes the image for screen readers. Leave empty if the image is decorative and the caption already says what it shows.', 'max_length': 250, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('alt_text', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 2), ('alt_text', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'max_num': 3, 'min_num': 2}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown under the row.', 'max_length': 250, 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('images', 8), ('caption', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 12: ('wagtail.blocks.URLBlock', (), {'help_text': 'A YouTube, Vimeo, or Facebook link. Leave empty if uploading a file.', 'required': False}), 13: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'An uploaded .mp4 or .webm, up to 100MB. Used when there is no link.', 'required': False}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Still shown before the video is played. YouTube links use their own thumbnail when this is empty.', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('url', 12), ('video_file', 13), ('caption', 6), ('poster', 14)]], {}), 16: ('wagtail.blocks.StreamBlock', [[('image', 5), ('video', 15)]], {'min_num': 1}), 17: ('wagtail.blocks.StructBlock', [[('heading', 11), ('items', 16), ('caption', 6)]], {}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': program.blocks.collection_choices, 'help_text': 'Images uploaded into this collection are shown, newest last.'}), 19: ('wagtail.blocks.StructBlock', [[('heading', 11), ('collection', 18), ('caption', 6)]], {}), 20: ('wagtail.blocks.TextBlock', (), {}), 21: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('text', 20), ('attribution', 21)]], {}), 23: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text on the download link. Defaults to the document title.', 'max_length': 120, 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('document', 23), ('label', 24)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'Project facts', 'max_length': 200, 'required': False}), 27: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 28: ('wagtail.blocks.CharBlock', (), {'max_length': 300}), 29: ('wagtail.blocks.StructBlock', [[('label', 27), ('value', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {'min_num': 1}), 31: ('wagtail.blocks.StructBlock', [[('heading', 26), ('facts', 30)]], {}), 32: ('wagtail.blocks.CharBlock', (), {'help_text': 'For example 42% or 1.8 kW.', 'max_length': 40}), 33: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 34: ('wagtail.blocks.StructBlock', [[('value', 32), ('label', 33)]], {}), 35: ('wagtail.blocks.ListBlock', (34,), {'max_num': 4, 'min_num': 2}), 36: ('wagtail.blocks.StructBlock', [[('heading', 11), ('stats', 35)]], {}), 37: ('wagtail.blocks.CharBlock', (), {'default': 'Method', 'max_length': 200, 'required': False}), 38: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 39: ('wagtail.blocks.TextBlock', (), {'required': False}), 40: ('wagtail.blocks.StructBlock', [[('title', 38), ('description', 39)]], {}), 41: ('wagtail.blocks.ListBlock', (40,), {'min_num': 1}), 42: ('wagtail.blocks.StructBlock', [[('heading', 37), ('steps', 41)]], {}), 43: ('wagtail.blocks.CharBlock', (), {'default': 'Project team', 'max_length': 200, 'required': False}), 44: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 45: ('wagtail.blocks.CharBlock', (), {'help_text': 'For example Student researcher, or Supervisor.', 'max_length': 160}), 46: ('wagtail.blocks.CharBlock', (), {'help_text': 'Year of study, department, or area of contribution.', 'max_length': 200, 'required': False}), 47: ('wagtail.blocks.StructBlock', [[('name', 44), ('role', 45), ('detail', 46)]], {}), 48: ('wagtail.blocks.ListBlock', (47,), {'min_num': 1}), 49: ('wagtail.blocks.StructBlock', [[('heading', 43), ('members', 48)]], {}), 50: ('wagtail.blocks.CharBlock', (), {'default': 'Project activities', 'max_length': 200, 'required': False}), 51: ('wagtail.blocks.CharBlock', (), {'help_text': 'For example March 2026, or 2025-2026.', 'max_length': 80}), 52: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('done', 'Completed'), ('current', 'In progress'), ('planned', 'Planned')]}), 53: ('wagtail.blocks.StructBlock', [[('period', 51), ('title', 38), ('detail', 39), ('status', 52)]], {}), 54: ('wagtail.blocks.ListBlock', (53,), {'min_num': 1}), 55: ('wagtail.blocks.StructBlock', [[('heading', 50), ('entries', 54)]], {}), 56: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 57: ('wagtail.blocks.StructBlock', [[('heading', 11), ('table', 56), ('caption', 6)]], {}), 58: ('wagtail.blocks.CharBlock', (), {'default': 'Note', 'max_length': 60, 'required': False}), 59: ('wagtail.blocks.StructBlock', [[('label', 58), ('text', 20)]], {}), 60: ('wagtail.blocks.CharBlock', (), {'default': 'Publications and references', 'max_length': 200, 'required': False}), 61: ('wagtail.blocks.URLBlock', (), {'required': False}), 62: ('wagtail.blocks.StructBlock', [[('citation', 20), ('url', 61)]], {}), 63: ('wagtail.blocks.ListBlock', (62,), {'min_num': 1}), 64: ('wagtail.blocks.StructBlock', [[('heading', 60), ('entries', 63)]], {})}, help_text='What the machine is, what it is for, its main parts and how it works. Numbered steps suit the parts list and the operating sequence; a callout suits a safety note or a formula. A machine with nothing written here keeps its catalogue card and has no page of its own.', verbose_name='Machine detail'),
        ),
        # Added blank, filled, then constrained: a unique column cannot be
        # introduced onto thirty rows that would all share an empty value.
        migrations.AddField(
            model_name='facility',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text="Web address for this machine's page. Left blank, it is made from the name.", max_length=200),
        ),
        migrations.RunPython(fill_slugs, clear_slugs),
        migrations.AlterField(
            model_name='facility',
            name='slug',
            field=models.SlugField(blank=True, help_text="Web address for this machine's page. Left blank, it is made from the name.", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.TextField(help_text='One or two sentences for the catalogue card.'),
        ),
    ]
