# Generated by Django 6.0.7 on 2026-10-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0029_research_project_platform_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsettings',
            name='entrance_prep_url',
            field=models.URLField(blank=True, help_text='Full address of the entrance preparation practice platform, for example https://prep.example.org. Leave this empty and no link to it appears anywhere on the site, so the platform can be taken down or moved without a code change.', verbose_name='Entrance preparation platform URL'),
        ),
    ]
